use crate::db::DatabaseDriver;
use crate::types::*;
use anyhow::{anyhow, Result};
use async_trait::async_trait;
use futures::stream::TryStreamExt;
use mongodb::bson::oid::ObjectId;
use mongodb::{
    bson::{doc, Bson, Document},
    options::{ClientOptions, FindOptions},
    Client,
};
use std::time::Instant;

fn bson_to_json(bson: &Bson) -> serde_json::Value {
    match bson {
        Bson::Double(v) => serde_json::Value::Number(
            serde_json::Number::from_f64(*v).unwrap_or(serde_json::Number::from(0)),
        ),
        Bson::String(v) => serde_json::Value::String(v.clone()),
        Bson::Boolean(v) => serde_json::Value::Bool(*v),
        Bson::Null => serde_json::Value::Null,
        Bson::Int32(v) => serde_json::Value::Number((*v).into()),
        Bson::Int64(v) => serde_json::Value::Number((*v).into()),
        Bson::ObjectId(oid) => serde_json::Value::String(oid.to_hex()),
        Bson::DateTime(dt) => serde_json::Value::String(dt.to_string()),
        Bson::Array(arr) => serde_json::Value::Array(arr.iter().map(bson_to_json).collect()),
        Bson::Document(doc) => {
            let mut map = serde_json::Map::new();
            for (k, v) in doc {
                map.insert(k.clone(), bson_to_json(v));
            }
            serde_json::Value::Object(map)
        }
        _ => serde_json::Value::String(bson.to_string()),
    }
}

/// Parse an `_id` string as ObjectId if possible, otherwise as a BSON string.
fn parse_bson_id(id_str: &str) -> Bson {
    if let Ok(oid) = ObjectId::parse_str(id_str) {
        Bson::ObjectId(oid)
    } else {
        Bson::String(id_str.to_string())
    }
}

// ── Simple SQL parsers (for UPDATE / DELETE generated by the frontend) ─────────

fn sql_unquote_name(s: &str) -> String {
    let s = s.trim();
    if s.len() >= 2
        && ((s.starts_with('"') && s.ends_with('"')) || (s.starts_with('`') && s.ends_with('`')))
    {
        s[1..s.len() - 1].replace("\"\"", "\"").replace("``", "`")
    } else {
        s.to_string()
    }
}

fn sql_unquote_value(s: &str) -> Option<String> {
    let s = s.trim();
    if s.eq_ignore_ascii_case("null") {
        None
    } else if s.len() >= 2 && s.starts_with('\'') && s.ends_with('\'') {
        Some(s[1..s.len() - 1].replace("''", "'"))
    } else {
        Some(s.to_string())
    }
}

/// Parse `UPDATE "collection" SET "field" = 'value' WHERE "_id" = 'oid'`
/// Returns `(collection, field, new_value, id_value)`.
fn parse_mongo_update(query: &str) -> Option<(String, String, Option<String>, String)> {
    let q = query.trim();
    let upper = q.to_ascii_uppercase();
    if !upper.starts_with("UPDATE ") {
        return None;
    }
    let set_pos = upper.find(" SET ")?;
    let collection = sql_unquote_name(q[7..set_pos].trim());

    let after_set = &q[set_pos + 5..];
    let upper_after = after_set.to_ascii_uppercase();
    let where_pos = upper_after.find(" WHERE ")?;

    let set_clause = after_set[..where_pos].trim();
    let where_str = &after_set[where_pos + 7..];

    // Parse SET field = value
    let eq_pos = set_clause.find('=')?;
    let field = sql_unquote_name(set_clause[..eq_pos].trim());
    let new_value = sql_unquote_value(set_clause[eq_pos + 1..].trim());

    // Extract _id value from WHERE
    let id_value = extract_id_from_where(where_str)?;

    Some((collection, field, new_value, id_value))
}

/// Parse `DELETE FROM "collection" WHERE "_id" = 'oid'`
/// Returns `(collection, id_value)`.
fn parse_mongo_delete(query: &str) -> Option<(String, String)> {
    let q = query.trim();
    let upper = q.to_ascii_uppercase();
    if !upper.starts_with("DELETE FROM ") {
        return None;
    }
    let where_pos = upper.find(" WHERE ")?;
    let collection = sql_unquote_name(q[12..where_pos].trim());
    let where_str = &q[where_pos + 7..];
    let id_value = extract_id_from_where(where_str)?;
    Some((collection, id_value))
}

/// Find `"_id" = 'value'` within a WHERE clause and return the value string.
fn extract_id_from_where(where_str: &str) -> Option<String> {
    let upper = where_str.to_ascii_uppercase();
    for term in &[r#""_ID""#, "`_ID`", "_ID "] {
        if let Some(kpos) = upper.find(term) {
            let after = &where_str[kpos + term.len()..];
            let eq = after.find('=')?;
            let after_eq = after[eq + 1..].trim();
            let end = after_eq
                .to_ascii_uppercase()
                .find(" AND ")
                .unwrap_or(after_eq.len());
            return sql_unquote_value(after_eq[..end].trim());
        }
    }
    None
}

// ─────────────────────────────────────────────────────────────────────────────

pub struct MongoDriver {
    pub client: tokio::sync::RwLock<Option<Client>>,
    /// Last-used database so SQL UPDATE/DELETE in run_query knows where to write.
    pub current_db: tokio::sync::RwLock<String>,
}

impl MongoDriver {
    pub fn new() -> Self {
        Self {
            client: tokio::sync::RwLock::new(None),
            current_db: tokio::sync::RwLock::new(String::new()),
        }
    }
}

#[async_trait]
impl DatabaseDriver for MongoDriver {
    async fn connect(&self, config: &ConnectionConfig) -> Result<()> {
        let uri = config
            .uri
            .as_deref()
            .ok_or_else(|| anyhow!("MongoDB URI required"))?;
        let options = ClientOptions::parse(uri).await?;
        let client = Client::with_options(options)?;

        // Ping the server to verify connection
        client
            .database("admin")
            .run_command(doc! {"ping": 1}, None)
            .await?;

        // Seed current_db from the connection config if provided.
        if let Some(db) = &config.database {
            *self.current_db.write().await = db.clone();
        }

        let mut client_lock = self.client.write().await;
        *client_lock = Some(client);
        Ok(())
    }

    async fn disconnect(&self) -> Result<()> {
        let mut client_lock = self.client.write().await;
        *client_lock = None;
        Ok(())
    }

    async fn get_databases(&self) -> Result<Vec<String>> {
        let client_lock = self.client.read().await;
        let client = client_lock
            .as_ref()
            .ok_or_else(|| anyhow!("Not connected"))?;

        Ok(client.list_database_names(None, None).await?)
    }

    async fn create_database(&self, name: &str) -> Result<()> {
        // MongoDB creates a database implicitly when a collection is inserted into.
        // We create a sentinel collection then drop it so the DB persists as empty.
        let client_lock = self.client.read().await;
        let client = client_lock
            .as_ref()
            .ok_or_else(|| anyhow!("Not connected"))?;

        let db = client.database(name);
        // Creating a collection forces the database to materialise on disk.
        db.create_collection("_init", None).await?;
        Ok(())
    }

    async fn get_schemas(&self, _database: &str) -> Result<Vec<String>> {
        Ok(vec!["collection".to_string()])
    }

    async fn get_tables(&self, database: &str, _schema: Option<&str>) -> Result<Vec<TableInfo>> {
        let client_lock = self.client.read().await;
        let client = client_lock
            .as_ref()
            .ok_or_else(|| anyhow!("Not connected"))?;

        *self.current_db.write().await = database.to_string();

        let db = client.database(database);
        let collections = db.list_collection_names(None).await?;

        Ok(collections
            .into_iter()
            .map(|name| TableInfo {
                name,
                schema: None,
                columns: None,
            })
            .collect())
    }

    async fn get_columns(
        &self,
        database: &str,
        table: &str,
        _schema: Option<&str>,
    ) -> Result<Vec<ColumnInfo>> {
        let client_lock = self.client.read().await;
        let client = client_lock
            .as_ref()
            .ok_or_else(|| anyhow!("Not connected"))?;

        // Sample one document to infer field names; always include _id as primary key.
        let db = client.database(database);
        let collection: mongodb::Collection<Document> = db.collection(table);

        let options = FindOptions::builder().limit(Some(1)).build();
        let mut cursor = collection.find(None, options).await?;

        let mut columns: Vec<ColumnInfo> = vec![ColumnInfo {
            name: "_id".to_string(),
            data_type: "ObjectId".to_string(),
            nullable: false,
            is_primary: true,
            is_unique: true,
            default_value: None,
            extra: None,
        }];

        if let Some(doc) = cursor.try_next().await? {
            for key in doc.keys() {
                if key == "_id" {
                    continue; // already added
                }
                let data_type = match doc.get(key) {
                    Some(Bson::Double(_)) => "Double",
                    Some(Bson::String(_)) => "String",
                    Some(Bson::Boolean(_)) => "Boolean",
                    Some(Bson::Int32(_)) => "Int32",
                    Some(Bson::Int64(_)) => "Int64",
                    Some(Bson::DateTime(_)) => "DateTime",
                    Some(Bson::Array(_)) => "Array",
                    Some(Bson::Document(_)) => "Document",
                    Some(Bson::ObjectId(_)) => "ObjectId",
                    _ => "Mixed",
                };
                columns.push(ColumnInfo {
                    name: key.clone(),
                    data_type: data_type.to_string(),
                    nullable: true,
                    is_primary: false,
                    is_unique: false,
                    default_value: None,
                    extra: None,
                });
            }
        }

        Ok(columns)
    }

    async fn run_query(&self, query_str: &str) -> Result<QueryResult> {
        let client_lock = self.client.read().await;
        let client = client_lock
            .as_ref()
            .ok_or_else(|| anyhow!("Not connected"))?;

        let start = Instant::now();
        let trimmed = query_str.trim();
        let upper = trimmed.to_ascii_uppercase();

        // ── SQL UPDATE → MongoDB updateOne ───────────────────────────────────
        if upper.starts_with("UPDATE ") {
            if let Some((collection_name, field, new_value, id_str)) = parse_mongo_update(trimmed) {
                let db_name = self.current_db.read().await.clone();
                if db_name.is_empty() {
                    return Err(anyhow!("No database selected"));
                }
                let db = client.database(&db_name);
                let collection: mongodb::Collection<Document> = db.collection(&collection_name);

                let filter = doc! { "_id": parse_bson_id(&id_str) };
                let update_value = match new_value {
                    Some(v) => Bson::String(v),
                    None => Bson::Null,
                };
                let update = doc! { "$set": { &field: update_value } };

                collection.update_one(filter, update, None).await?;
                let duration = start.elapsed().as_millis() as u64;
                return Ok(QueryResult {
                    columns: vec!["result".to_string()],
                    rows: vec![serde_json::json!({"result": "OK"})],
                    execution_time_ms: duration,
                });
            }
        }

        // ── SQL DELETE FROM → MongoDB deleteOne ──────────────────────────────
        if upper.starts_with("DELETE FROM ") {
            if let Some((collection_name, id_str)) = parse_mongo_delete(trimmed) {
                let db_name = self.current_db.read().await.clone();
                if db_name.is_empty() {
                    return Err(anyhow!("No database selected"));
                }
                let db = client.database(&db_name);
                let collection: mongodb::Collection<Document> = db.collection(&collection_name);

                let filter = doc! { "_id": parse_bson_id(&id_str) };
                collection.delete_one(filter, None).await?;
                let duration = start.elapsed().as_millis() as u64;
                return Ok(QueryResult {
                    columns: vec!["result".to_string()],
                    rows: vec![serde_json::json!({"result": "OK"})],
                    execution_time_ms: duration,
                });
            }
        }

        // ── Existing JSON query format ────────────────────────────────────────
        let query_json: serde_json::Value =
            serde_json::from_str(trimmed).map_err(|e| anyhow!("Invalid query JSON: {}", e))?;

        let database = query_json["db"]
            .as_str()
            .ok_or_else(|| anyhow!("Missing 'db' field"))?;
        let collection_name = query_json["collection"]
            .as_str()
            .ok_or_else(|| anyhow!("Missing 'collection' field"))?;
        let limit = query_json["limit"].as_i64().unwrap_or(100);

        let filter = if let Some(f) = query_json.get("filter") {
            mongodb::bson::to_document(f).unwrap_or_default()
        } else {
            Document::new()
        };

        let db = client.database(database);
        let collection: mongodb::Collection<Document> = db.collection(collection_name);

        let options = FindOptions::builder().limit(Some(limit)).build();

        let mut cursor = collection.find(filter, options).await?;
        let mut rows: Vec<serde_json::Value> = Vec::new();
        let mut columns: Vec<String> = Vec::new();
        let mut docs: Vec<Document> = Vec::new();

        while let Some(doc) = cursor.try_next().await? {
            for key in doc.keys() {
                if !columns.contains(key) {
                    columns.push(key.clone());
                }
            }
            docs.push(doc);
        }

        for doc in docs {
            let mut row = serde_json::Map::new();
            for key in &columns {
                let val = doc
                    .get(key)
                    .map(bson_to_json)
                    .unwrap_or(serde_json::Value::Null);
                row.insert(key.clone(), val);
            }
            rows.push(serde_json::Value::Object(row));
        }

        Ok(QueryResult {
            columns,
            rows,
            execution_time_ms: start.elapsed().as_millis() as u64,
        })
    }

    async fn get_table_data(
        &self,
        database: &str,
        table: &str,
        page: u32,
        page_size: u32,
    ) -> Result<QueryResult> {
        let client_lock = self.client.read().await;
        let client = client_lock
            .as_ref()
            .ok_or_else(|| anyhow!("Not connected"))?;

        let start = Instant::now();
        let skip = (page * page_size) as u64;

        *self.current_db.write().await = database.to_string();

        let db = client.database(database);
        let collection: mongodb::Collection<Document> = db.collection(table);

        let options = FindOptions::builder()
            .skip(Some(skip))
            .limit(Some(page_size as i64))
            .build();

        let mut cursor = collection.find(None, options).await?;
        let mut columns: Vec<String> = Vec::new();
        let mut docs: Vec<Document> = Vec::new();

        while let Some(doc) = cursor.try_next().await? {
            for key in doc.keys() {
                if !columns.contains(key) {
                    columns.push(key.clone());
                }
            }
            docs.push(doc);
        }
        let mut rows: Vec<serde_json::Value> = Vec::new();

        for doc in docs {
            let mut row = serde_json::Map::new();
            for key in &columns {
                let val = doc
                    .get(key)
                    .map(bson_to_json)
                    .unwrap_or(serde_json::Value::Null);
                row.insert(key.clone(), val);
            }
            rows.push(serde_json::Value::Object(row));
        }

        Ok(QueryResult {
            columns,
            rows,
            execution_time_ms: start.elapsed().as_millis() as u64,
        })
    }
}
