import { useState, useMemo } from "react";
import {
	ArrowLeft,
	ArrowRightLeft,
	Plus,
	Minus,
	RefreshCw,
	Copy,
	Check,
	ChevronDown,
	ChevronRight,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { ScrollArea } from "@/components/ui/scroll-area";
import { cn } from "@/lib/utils";
import { useAppStore } from "@/store/useAppStore";
import { tauriApi } from "@/lib/tauri-api";
import { toast } from "@/components/ui/sonner";
import type { SchemaDiff, TableDiff, ColumnDiff, SchemaGraphTable, ForeignKeyRelation, RelationshipDiff, DiffStatus } from "@/types";

// ── Diff computation ─────────────────────────────────────────────────────────

function computeSchemaDiff(
	tablesA: SchemaGraphTable[],
	relsA: ForeignKeyRelation[],
	tablesB: SchemaGraphTable[],
	relsB: ForeignKeyRelation[],
): SchemaDiff {
	const mapA = new Map(tablesA.map((t) => [t.name, t]));
	const mapB = new Map(tablesB.map((t) => [t.name, t]));
	const allTableNames = new Set([...mapA.keys(), ...mapB.keys()]);

	const tableDiffs: TableDiff[] = [];
	let addedCount = 0, removedCount = 0, changedCount = 0;

	for (const name of allTableNames) {
		const ta = mapA.get(name);
		const tb = mapB.get(name);
		if (!ta) {
			addedCount++;
			tableDiffs.push({ name, status: "added", columnDiffs: (tb!.columns ?? []).map((c) => ({ name: c.name, status: "added", after: c })) });
		} else if (!tb) {
			removedCount++;
			tableDiffs.push({ name, status: "removed", columnDiffs: (ta.columns ?? []).map((c) => ({ name: c.name, status: "removed", before: c })) });
		} else {
			const colsA = new Map((ta.columns ?? []).map((c) => [c.name, c]));
			const colsB = new Map((tb.columns ?? []).map((c) => [c.name, c]));
			const allCols = new Set([...colsA.keys(), ...colsB.keys()]);
			const columnDiffs: ColumnDiff[] = [];
			for (const col of allCols) {
				const ca = colsA.get(col);
				const cb = colsB.get(col);
				if (!ca) columnDiffs.push({ name: col, status: "added", after: cb });
				else if (!cb) columnDiffs.push({ name: col, status: "removed", before: ca });
				else if (ca.dataType !== cb.dataType || ca.nullable !== cb.nullable || ca.isPrimary !== cb.isPrimary)
					columnDiffs.push({ name: col, status: "changed", before: ca, after: cb });
				else columnDiffs.push({ name: col, status: "unchanged", before: ca, after: cb });
			}
			const hasChanges = columnDiffs.some((c) => c.status !== "unchanged");
			if (hasChanges) changedCount++;
			tableDiffs.push({ name, status: hasChanges ? "changed" : "unchanged", columnDiffs });
		}
	}

	// Sort: added first, removed, changed, unchanged
	const order: Record<DiffStatus, number> = { added: 0, removed: 1, changed: 2, unchanged: 3 };
	tableDiffs.sort((a, b) => order[a.status] - order[b.status] || a.name.localeCompare(b.name));

	// Relationship diffs
	const mapRa = new Map(relsA.map((r) => [r.name, r]));
	const mapRb = new Map(relsB.map((r) => [r.name, r]));
	const allRels = new Set([...mapRa.keys(), ...mapRb.keys()]);
	const relationshipDiffs: RelationshipDiff[] = [];
	for (const name of allRels) {
		const ra = mapRa.get(name);
		const rb = mapRb.get(name);
		if (!ra) relationshipDiffs.push({ name, status: "added", after: rb });
		else if (!rb) relationshipDiffs.push({ name, status: "removed", before: ra });
		else relationshipDiffs.push({ name, status: "unchanged", before: ra, after: rb });
	}

	return { tableDiffs, relationshipDiffs, addedCount, removedCount, changedCount };
}

// ── Migration SQL generation ─────────────────────────────────────────────────

function generateMigrationSql(diff: SchemaDiff): string {
	const lines: string[] = ["-- Migration generated by DB Connect", "-- Apply to bring Source schema up to Target", ""];
	for (const td of diff.tableDiffs) {
		if (td.status === "added") {
			const cols = td.columnDiffs
				.filter((c) => c.after)
				.map((c) => {
					const col = c.after!;
					const pk = col.isPrimary ? " PRIMARY KEY" : "";
					const nn = !col.nullable && !col.isPrimary ? " NOT NULL" : "";
					const def = col.defaultValue ? ` DEFAULT ${col.defaultValue}` : "";
					return `  ${col.name} ${col.dataType}${pk}${nn}${def}`;
				})
				.join(",\n");
			lines.push(`CREATE TABLE ${td.name} (\n${cols}\n);`, "");
		} else if (td.status === "removed") {
			lines.push(`DROP TABLE IF EXISTS ${td.name};`, "");
		} else if (td.status === "changed") {
			for (const cd of td.columnDiffs) {
				if (cd.status === "added" && cd.after) {
					const nn = !cd.after.nullable ? " NOT NULL" : "";
					const def = cd.after.defaultValue ? ` DEFAULT ${cd.after.defaultValue}` : "";
					lines.push(`ALTER TABLE ${td.name} ADD COLUMN ${cd.after.name} ${cd.after.dataType}${nn}${def};`);
				} else if (cd.status === "removed") {
					lines.push(`ALTER TABLE ${td.name} DROP COLUMN ${cd.name};`);
				} else if (cd.status === "changed" && cd.after) {
					lines.push(`-- Changed: ${td.name}.${cd.name} (${cd.before?.dataType} → ${cd.after.dataType})`);
					lines.push(`ALTER TABLE ${td.name} ALTER COLUMN ${cd.name} TYPE ${cd.after.dataType};`);
				}
			}
			lines.push("");
		}
	}
	if (lines[lines.length - 1] === "") lines.pop();
	return lines.join("\n");
}

// ── Sub-components ────────────────────────────────────────────────────────────

function StatusBadge({ status }: { status: DiffStatus }) {
	if (status === "added") return <span className="flex items-center gap-0.5 text-[10px] font-semibold text-success"><Plus size={9} />added</span>;
	if (status === "removed") return <span className="flex items-center gap-0.5 text-[10px] font-semibold text-destructive"><Minus size={9} />removed</span>;
	if (status === "changed") return <span className="text-[10px] font-semibold text-warning">changed</span>;
	return null;
}

function TableDiffRow({ td }: { td: TableDiff }) {
	const [open, setOpen] = useState(td.status !== "unchanged");
	const changedCols = td.columnDiffs.filter((c) => c.status !== "unchanged");

	return (
		<div className={cn("rounded border", td.status === "added" && "border-success/25 bg-success/5", td.status === "removed" && "border-destructive/25 bg-destructive/5", td.status === "changed" && "border-warning/25 bg-warning/5", td.status === "unchanged" && "border-border/40")}>
			<button
				onClick={() => setOpen((v) => !v)}
				className="flex w-full items-center gap-2 px-3 py-2 text-left"
			>
				{open ? <ChevronDown size={11} className="shrink-0 text-foreground/40" /> : <ChevronRight size={11} className="shrink-0 text-foreground/40" />}
				<span className="flex-1 text-[12px] font-medium font-mono">{td.name}</span>
				<StatusBadge status={td.status} />
				{td.status === "changed" && (
					<span className="text-[10px] text-foreground/50">{changedCols.length} column{changedCols.length !== 1 ? "s" : ""} changed</span>
				)}
			</button>
			{open && td.columnDiffs.length > 0 && (
				<div className="border-t border-border/30 px-3 pb-2 pt-1">
					<table className="w-full text-[11px]">
						<thead>
							<tr className="text-foreground/40">
								<th className="py-1 text-left font-medium">Column</th>
								<th className="py-1 text-left font-medium">Source type</th>
								<th className="py-1 text-left font-medium">Target type</th>
								<th className="py-1 text-left font-medium" />
							</tr>
						</thead>
						<tbody>
							{td.columnDiffs.map((cd) => (
								<tr key={cd.name} className={cn("border-t border-border/20", cd.status === "unchanged" && "opacity-40")}>
									<td className="py-1 font-mono">{cd.name}</td>
									<td className={cn("py-1 font-mono", cd.status === "removed" && "text-destructive line-through")}>
										{cd.before?.dataType ?? "—"}
									</td>
									<td className={cn("py-1 font-mono", cd.status === "added" && "text-success")}>
										{cd.after?.dataType ?? "—"}
									</td>
									<td className="py-1 text-right">
										<StatusBadge status={cd.status} />
									</td>
								</tr>
							))}
						</tbody>
					</table>
				</div>
			)}
		</div>
	);
}

// ── Connection/DB picker ──────────────────────────────────────────────────────

function SideSelector({
	label,
	connectionId,
	database,
	onConnectionChange,
	onDatabaseChange,
}: {
	label: string;
	connectionId: string;
	database: string;
	onConnectionChange: (id: string) => void;
	onDatabaseChange: (db: string) => void;
}) {
	const { connections, connectedIds, connectionDatabases } = useAppStore();
	const dbs = connectionId ? (connectionDatabases[connectionId] ?? []) : [];
	return (
		<div className="flex flex-col gap-1.5">
			<span className="text-[10px] font-bold uppercase tracking-widest text-foreground/50">{label}</span>
			<select
				className="h-8 rounded border border-border bg-surface-2 px-2 text-[12px] text-foreground"
				value={connectionId}
				onChange={(e) => { onConnectionChange(e.target.value); onDatabaseChange(""); }}
			>
				<option value="">— Select connection —</option>
				{connections.filter((c) => connectedIds.includes(c.id)).map((c) => (
					<option key={c.id} value={c.id}>{c.name}</option>
				))}
			</select>
			{connectionId && (
				<select
					className="h-8 rounded border border-border bg-surface-2 px-2 text-[12px] text-foreground"
					value={database}
					onChange={(e) => onDatabaseChange(e.target.value)}
				>
					<option value="">— Select database —</option>
					{dbs.map((db) => (
						<option key={db} value={db}>{db}</option>
					))}
				</select>
			)}
		</div>
	);
}

// ── Main view ─────────────────────────────────────────────────────────────────

export function SchemaDiffView() {
	const { setActiveView } = useAppStore();

	const [srcConnId, setSrcConnId] = useState("");
	const [srcDb, setSrcDb] = useState("");
	const [tgtConnId, setTgtConnId] = useState("");
	const [tgtDb, setTgtDb] = useState("");
	const [diff, setDiff] = useState<SchemaDiff | null>(null);
	const [loading, setLoading] = useState(false);
	const [migrationSql, setMigrationSql] = useState<string | null>(null);
	const [copied, setCopied] = useState(false);
	const [showUnchanged, setShowUnchanged] = useState(false);

	const canCompare = srcConnId && srcDb && tgtConnId && tgtDb;

	const handleCompare = async () => {
		if (!canCompare) return;
		setLoading(true);
		setDiff(null);
		setMigrationSql(null);
		try {
			const [graphA, graphB] = await Promise.all([
				tauriApi.getSchemaGraph(srcConnId, srcDb),
				tauriApi.getSchemaGraph(tgtConnId, tgtDb),
			]);
			const result = computeSchemaDiff(graphA.tables, graphA.relationships, graphB.tables, graphB.relationships);
			setDiff(result);
		} catch (e: any) {
			toast.error(String(e));
		} finally {
			setLoading(false);
		}
	};

	const handleGenerateMigration = () => {
		if (!diff) return;
		const sql = generateMigrationSql(diff);
		setMigrationSql(sql);
	};

	const handleCopySql = () => {
		if (!migrationSql) return;
		navigator.clipboard.writeText(migrationSql).then(() => {
			setCopied(true);
			setTimeout(() => setCopied(false), 2000);
		});
	};

	const visibleDiffs = useMemo(
		() => diff?.tableDiffs.filter((t) => showUnchanged || t.status !== "unchanged") ?? [],
		[diff, showUnchanged],
	);

	return (
		<div className="flex h-full flex-col bg-surface-1">
			{/* Header */}
			<div className="shell-toolbar flex h-10 shrink-0 items-center gap-3 border-b px-4">
				<Button variant="ghost" size="icon-xs" onClick={() => setActiveView("main")} className="h-7 w-7 text-foreground/60">
					<ArrowLeft size={13} />
				</Button>
				<ArrowRightLeft size={13} className="text-foreground/50" />
				<span className="text-[13px] font-semibold">Schema Diff</span>
				<span className="text-foreground/30">·</span>
				<span className="text-[11px] text-foreground/50">Compare two databases and generate a migration script</span>
			</div>

			{/* Picker row */}
			<div className="shrink-0 border-b bg-surface-2 px-6 py-4">
				<div className="flex items-end gap-4">
					<SideSelector
						label="Source (from)"
						connectionId={srcConnId}
						database={srcDb}
						onConnectionChange={setSrcConnId}
						onDatabaseChange={setSrcDb}
					/>
					<div className="mb-2 text-foreground/30"><ArrowRightLeft size={14} /></div>
					<SideSelector
						label="Target (to)"
						connectionId={tgtConnId}
						database={tgtDb}
						onConnectionChange={setTgtConnId}
						onDatabaseChange={setTgtDb}
					/>
					<Button
						onClick={handleCompare}
						disabled={!canCompare || loading}
						className="mb-0 h-8 gap-1.5 px-4 text-[12px]"
					>
						{loading ? <RefreshCw size={11} className="animate-spin" /> : <ArrowRightLeft size={11} />}
						Compare
					</Button>
				</div>
			</div>

			{/* Results */}
			{diff && (
				<div className="flex min-h-0 flex-1 flex-col overflow-hidden">
					{/* Summary bar */}
					<div className="flex shrink-0 items-center gap-4 border-b bg-surface-2 px-6 py-2">
						{diff.addedCount > 0 && <Badge variant="outline" className="gap-1 border-success/40 text-success"><Plus size={9} />{diff.addedCount} added</Badge>}
						{diff.removedCount > 0 && <Badge variant="outline" className="gap-1 border-destructive/40 text-destructive"><Minus size={9} />{diff.removedCount} removed</Badge>}
						{diff.changedCount > 0 && <Badge variant="outline" className="gap-1 border-warning/40 text-warning">{diff.changedCount} changed</Badge>}
						{diff.addedCount === 0 && diff.removedCount === 0 && diff.changedCount === 0 && (
							<span className="text-[11px] text-success">Schemas are identical</span>
						)}
						<div className="ml-auto flex items-center gap-2">
							<label className="flex cursor-pointer items-center gap-1.5 text-[11px] text-foreground/60">
								<input type="checkbox" checked={showUnchanged} onChange={(e) => setShowUnchanged(e.target.checked)} className="h-3 w-3" />
								Show unchanged
							</label>
							<Button variant="outline" size="sm" className="h-7 gap-1.5 px-3 text-[11px]" onClick={handleGenerateMigration}>
								Generate migration SQL
							</Button>
						</div>
					</div>

					<div className="flex min-h-0 flex-1 overflow-hidden">
						{/* Table diffs list */}
						<ScrollArea className="flex-1 border-r">
							<div className="flex flex-col gap-2 p-4">
								{visibleDiffs.length === 0 ? (
									<p className="text-center text-[12px] text-foreground/40 py-8">No differences found</p>
								) : (
									visibleDiffs.map((td) => <TableDiffRow key={td.name} td={td} />)
								)}
							</div>
						</ScrollArea>

						{/* Migration SQL panel */}
						{migrationSql !== null && (
							<div className="flex w-96 shrink-0 flex-col border-l bg-surface-2">
								<div className="flex shrink-0 items-center justify-between border-b px-3 py-2">
									<span className="text-[11px] font-semibold text-foreground/70">Migration SQL</span>
									<Button variant="ghost" size="icon-xs" className="h-6 w-6 text-foreground/50" onClick={handleCopySql}>
										{copied ? <Check size={10} className="text-success" /> : <Copy size={10} />}
									</Button>
								</div>
								<ScrollArea className="flex-1">
									<pre className="p-3 text-[11px] font-mono text-foreground/80 whitespace-pre-wrap leading-relaxed">
										{migrationSql}
									</pre>
								</ScrollArea>
							</div>
						)}
					</div>
				</div>
			)}

			{!diff && !loading && (
				<div className="flex flex-1 items-center justify-center">
					<p className="text-[12px] text-foreground/40">Select source and target databases, then click Compare</p>
				</div>
			)}
		</div>
	);
}
